from schemas.address import AddressSchema
from schemas.brand import BrandSchema
from schemas.charger import ChargerSchema
from schemas.city import CitySchema
from schemas.country import CountrySchema
from schemas.neighborhood import NeighborhoodSchema
from schemas.state import StateSchema
from schemas.status import StatusSchema
from schemas.type import TypeSchema
from schemas.error import ErrorSchema